# Form implementation generated from reading ui file 'add_people.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QFileDialog
from PyQt6.QtGui import QPixmap, QImage, QGuiApplication
import cv2
import sql_class
from PyQt6.QtCore import Qt
from facenet.encoding import encoding


widget_css="""
            /* General Widget Style */
            QWidget {
                font-family: 'Arial', sans-serif;
                background-color: #f2f2f2;
                color: #333;
                border-radius: 5px;
            }

            /* Label Styles */
            QLabel {
                font-size: 12pt;
                color: #444;
            }

            QLabel#name, QLabel#ID, QLabel#gender, QLabel#phone {
                font-weight: bold;
                color: #555;
                padding: 5px;
            }

            /* LineEdit Styles */
            QLineEdit {
                background-color: #fff;
                border: 2px solid #ddd;
                border-radius: 5px;
                padding: 5px;
                font-size: 10pt;
                margin: 5px;
            }

            QLineEdit:focus {
                border-color: #0078d4;
                background-color: #f8f8f8;
            }

            /* Button Styles */
            QPushButton {
                background-color: #4CAF50;
                color: white;
                border: none;
                padding: 10px 20px;
                font-size: 10pt;
                border-radius: 5px;
                cursor: pointer;
                transition: background-color 0.3s;
            }

            QPushButton:hover {
                background-color: #45a049;
            }

            QPushButton:pressed {
                background-color: #388e3c;
            }

            /* Button for delete */
            QPushButton#btn_delete {
                background-color: #f44336;
            }

            QPushButton#btn_delete:hover {
                background-color: #e53935;
            }

            QPushButton#btn_delete:pressed {
                background-color: #d32f2f;
            }

            /* Button for finish */
            QPushButton#btn_finish {
                background-color: #2196F3;
            }

            QPushButton#btn_finish:hover {
                background-color: #1976D2;
            }

            QPushButton#btn_finish:pressed {
                background-color: #1565C0;
            }

            /* Add photo label styling */
            QLabel#add_photo {
                border: 2px dashed #ddd;
                width: 80px;
                height: 80px;
                background-color: #e0e0e0;
                border-radius: 5px;
                display: flex;
                justify-content: center;
                align-items: center;
                font-size: 12pt;
                color: #888;
            }

            QLabel#add_photo:hover {
                background-color: #c1c1c1;
            }

            /* Layout of the form */
            QWidget {
                padding: 20px;
            }

            /* Position of elements */
            QLineEdit, QPushButton {
                margin-top: 10px;
            }

            QPushButton#btn_add_photo {
                background-color: #03a9f4;
                padding: 10px 15px;
            }
        """

class Ui_add_people(QtWidgets.QWidget):
    def __init__(self, mainwindow, retinaface):
        super().__init__()
        self.retinaface = retinaface
        self.mainwindow = mainwindow
        self.sql_class = sql_class.sql_class_add_people('localhost', 'root', 'root', 'photo', 'photo_list')
        self.cach_path = ''
        self.setObjectName("Form")
        self.resize(640, 540)

        # Layout managers
        main_layout = QtWidgets.QVBoxLayout(self)

        form_layout = QtWidgets.QGridLayout()
        main_layout.addLayout(form_layout)

        # Labels and Input Fields
        self.name = QtWidgets.QLabel("Name:")
        self.ID = QtWidgets.QLabel("ID:")
        self.gender = QtWidgets.QLabel("Gender:")
        self.phone = QtWidgets.QLabel("Phone:")

        self.name_edit = QtWidgets.QLineEdit()
        self.ID_edit = QtWidgets.QLineEdit()
        self.gender_edit = QtWidgets.QLineEdit()
        self.phone_edit = QtWidgets.QLineEdit()

        # Adding widgets to grid layout
        form_layout.addWidget(self.name, 0, 0)
        form_layout.addWidget(self.name_edit, 0, 1)
        form_layout.addWidget(self.ID, 1, 0)
        form_layout.addWidget(self.ID_edit, 1, 1)
        form_layout.addWidget(self.gender, 2, 0)
        form_layout.addWidget(self.gender_edit, 2, 1)
        form_layout.addWidget(self.phone, 3, 0)
        form_layout.addWidget(self.phone_edit, 3, 1)

        # Photo area
        self.add_photo = QtWidgets.QLabel("Add Photo")
        self.add_photo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.add_photo.setStyleSheet("""
            border: 2px dashed #ddd;
            background-color: #f0f0f0;
            height: 100px;
            width: 100px;
            border-radius: 10px;
        """)
        self.add_photo.setMinimumSize(100, 100)
        form_layout.addWidget(self.add_photo, 4, 0, 1, 2)

        # Buttons
        button_layout = QtWidgets.QHBoxLayout()
        main_layout.addLayout(button_layout)

        self.btn_add_photo = QtWidgets.QPushButton("Add Photo")
        self.btn_delete = QtWidgets.QPushButton("Delete")
        self.btn_finish = QtWidgets.QPushButton("Finish")

        button_layout.addWidget(self.btn_add_photo)
        button_layout.addWidget(self.btn_delete)
        button_layout.addWidget(self.btn_finish)

        # Connect buttons
        self.btn_add_photo.clicked.connect(lambda: self.choose_photo())
        self.btn_finish.clicked.connect(lambda: self.finish())
        self.btn_delete.clicked.connect(lambda: self.delete())
        self.setStyleSheet(widget_css)

    def choose_photo(self):
        file_path, _ = QFileDialog.getOpenFileName(self, "选择文件", "", "All Files (*)")
        if file_path:
            self.cach_path=file_path
            print(self.cach_path)
            self.lab_show(self.cach_path)
            QtWidgets.QMessageBox.information(self, "成功", "照片选择成功！")
        else:
            print('Photo is not exsits')

    def lab_show(self,path):
        frame = cv2.imread(path)
        height, width, channel = frame.shape
        img = QImage(frame.data, width, height, QImage.Format.Format_RGB888)
        img = img.rgbSwapped()
        pixmap = QPixmap.fromImage(img)
        lbl_width = self.phone.size().width()  # 通过size()获取图像标签的真实的宽度
        lbl_height = self.phone.size().height()  # 通过size()获取图像标签的真实的高度
        pixmap = QPixmap(pixmap).scaled(
            lbl_width, lbl_height,
            aspectRatioMode=Qt.AspectRatioMode.KeepAspectRatio)
        self.add_photo.setPixmap(pixmap)  # 在标签上显示图片

    def change_video_show(self, show, close):
        show.show()
        close.hide()

    def finish(self):
        self.sql_class.create_database()
        if self.name_edit.text() == '' or self.gender_edit.text() =='' or self.cach_path==''or  self.ID_edit.text()=='' or self.phone_edit.text() =='':
            QtWidgets.QMessageBox.warning(self, "错误", "信息不完整，请填写所有字段！")
            return

        try:
            with open(self.cach_path, "rb") as file:
                binary_data = file.read()
                self.sql_class.photo_insert(self.name_edit.text(),self.ID_edit.text(),self.gender_edit.text(),self.phone_edit.text(),binary_data)

            data = ''
            with open('./param.txt', 'r') as f:
                param = f.readlines()
                param[0] = str(int(param[0]))
                param[1] = str(self.retinaface.face_num+1)
                print(param[1])
                for i in param:
                    if i!='\n':
                        data += i+'\n'

            with open('./param.txt', 'w') as f:
                f.write(data)

            encoding(self.sql_class)
            self.retinaface.create_weight(0)
            QtWidgets.QMessageBox.information(self, "成功", "人脸添加成功！")
            self.change_video_show(self.mainwindow,self)
            self.cach_path = ''
            self.add_photo.setText("photo")
            self.name_edit.setText("")
            self.ID_edit.setText("")
            self.gender_edit.setText("")
            self.phone_edit.setText("")
        except Exception as e:
            QtWidgets.QMessageBox.critical(self, "错误", f"添加人脸失败：{str(e)}")

    def delete(self):
        if self.ID_edit.text()!="":
            try:
                self.sql_class.photo_delete(self.ID_edit.text())

                data = ''
                with open('./param.txt', 'r') as f:
                    param = f.readlines()
                    param[0] = str(int(param[0]))
                    param[1] = str(int(param[1]) - 1)
                    for i in param:
                        if i != '\n':
                            data += i + '\n'

                with open('./param.txt', 'w') as f:
                    f.write(data)
                encoding(self.sql_class)
                QtWidgets.QMessageBox.information(self, "成功", "人脸删除成功！")
                self.ID_edit.setText("")
            except Exception as e:
                QtWidgets.QMessageBox.critical(self, "错误", f"删除人脸失败：{str(e)}")
        else:
            QtWidgets.QMessageBox.warning(self, "错误", "ID不能为空！")