# Form implementation generated from reading ui file 'show.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from PyQt6.QtWidgets import QApplication, QLabel, QScrollArea, QVBoxLayout, QWidget
import sys

widget_css="""
            QWidget {
                background-color: #f8f8f8;
                font-family: 'Arial', sans-serif;
            }
            QLabel {
                font-size: 16px;
                color: #333;
                padding: 10px;
                font-weight: bold;
            }
            QComboBox {
                padding: 5px;
                font-size: 14px;
                background-color: #fff;
                color: #333;
                border: 1px solid #ccc;
                border-radius: 5px;
                height: 30px;
            }
            QComboBox:hover {
                border-color: #5b9bd5;
            }
            QComboBox QAbstractItemView {
                color: #333;
                background-color: #fff;
            }
            QPushButton {
                padding: 10px;
                font-size: 16px;
                background-color: #4CAF50;
                color: white;
                border: none;
                border-radius: 5px;
                width: 120px;
                height: 40px;
                margin-top: 20px;
            }
            QPushButton:hover {
                background-color: #45a049;
            }
            QPushButton:pressed {
                background-color: #397c39;
            }
            QVBoxLayout {
                margin: 0;
                padding: 20px;
            }
        """

class show_widget(QtWidgets.QWidget):
    def __init__(self, sql_class, detail_widget):
        super().__init__()
        self.detail_widget = detail_widget
        self.sql_class = sql_class

        self.setObjectName("Form")
        self.resize(640, 540)  # 设置窗口大小

        # 创建控件
        self.comboBox = QtWidgets.QComboBox(parent=self)
        self.comboBox.setObjectName("comboBox")

        self.btn_right = QtWidgets.QPushButton(parent=self)
        self.btn_right.setObjectName("right")

        self.label = QtWidgets.QLabel(parent=self)
        self.label.setObjectName("label")

        # 设置控件位置
        self.comboBox.setGeometry(QtCore.QRect(220, 180, 200, 30))  # 调整位置和大小
        self.btn_right.setGeometry(QtCore.QRect(270, 240, 100, 35))  # 调整按钮大小和位置
        self.label.setGeometry(QtCore.QRect(120, 120, 400, 30))  # 调整标签位置和大小

        # 设置布局
        self.layout = QtWidgets.QVBoxLayout(self)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setSpacing(20)

        self.layout.addWidget(self.label, alignment=QtCore.Qt.AlignmentFlag.AlignCenter)
        self.layout.addWidget(self.comboBox, alignment=QtCore.Qt.AlignmentFlag.AlignCenter)
        self.layout.addWidget(self.btn_right, alignment=QtCore.Qt.AlignmentFlag.AlignCenter)

        # 信号与槽连接
        self.btn_right.clicked.connect(lambda: self.show_all(self.detail_widget, self))

        # 设置窗口标题
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "ID选择窗口"))
        self.btn_right.setText(_translate("Form", "确认"))
        self.label.setText(_translate("Form", "选择要检查的ID号，如果为空则全部检查"))

        # 应用CSS样式
        self.setStyleSheet(widget_css)


    def show_all(self, show, close):
        if self.comboBox.currentText()=="None":
            print("---------------------------")
            all=self.sql_class.read_photo_list()
            list=[]
            for i in all:
                print(i[5])
                string = f"ID: {i[1]}\n姓名: {i[0]}\n违规次数: {str(i[5])}\n"
                list.append(string)
            string='\n'.join(list)
            self.detail_widget.label_show.setText(string)

        else:
            list=[]
            all=self.sql_class.read_ID(self.comboBox.currentText())
            for i in all:
                # 显示基本信息
                basic_info = f"ID: {i[1]}\n姓名: {i[0]}\n违规次数: {str(i[5])}\n"
                list.append(basic_info)
                
                # 显示详细违规记录
                try:
                    logs = self.sql_class.read_violation_logs()
                    if logs:
                        list.append("详细违规记录：")
                        for log in logs:
                            if log[2] == i[1]:  # 匹配当前ID
                                log_info = f"- 时间: {log[4]}\n  地点: {log[3]}\n  类型: {log[5]}\n  置信度: {log[6]}\n"
                                list.append(log_info)
                except Exception as e:
                    print(f"读取违规日志失败: {e}")
            
            string='\n'.join(list)
            self.detail_widget.label_show.setText(string)

        show.show()
        close.hide()

