# Form implementation generated from reading ui file 'video_change.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

widget_css="""
            QWidget#video_change {
                background-color: #f0f0f0;
            }

            QLineEdit {
                padding: 5px;
                font-size: 14px;
                border: 1px solid #ccc;
                border-radius: 5px;
                background-color: #fff;
            }

            QLineEdit:focus {
                border: 1px solid #5b9bd5;
                background-color: #e6f0fa;
            }

            QPushButton {
                padding: 8px 15px;
                font-size: 14px;
                border: 1px solid #5b9bd5;
                border-radius: 5px;
                background-color: #5b9bd5;
                color: white;
                margin: 10px;
            }

            QPushButton:hover {
                background-color: #4a89c2;
            }

            QPushButton:pressed {
                background-color: #397baf;
            }

            QLabel {
                font-size: 14px;
                color: #333;
                margin-left: 5px;
            }

            QFormLayout {
                margin-top: 30px;
                margin-left: 20px;
                margin-right: 20px;
            }

            QVBoxLayout {
                padding: 20px;
            }
        """

class Ui_video_change(QtWidgets.QWidget):
    def __init__(self, video_cap_list, mainwindow, sql_class):
        super().__init__()
        self.sql_class = sql_class
        self.mainwindow = mainwindow
        self.video_cap_list = video_cap_list  # 摄像头字典对象 存放key=名称 value=[ip,账号,密码]
        self.setObjectName("video_change")
        self.resize(640, 540)

        # 创建布局
        self.main_layout = QtWidgets.QVBoxLayout(self)

        # 控件布局 - 表单部分
        self.form_layout = QtWidgets.QFormLayout()
        self.main_layout.addLayout(self.form_layout)

        # 创建控件
        self.name_edit = QtWidgets.QLineEdit(self)
        self.IP_edit = QtWidgets.QLineEdit(self)
        self.zhanghao_edit = QtWidgets.QLineEdit(self)
        self.mima_edit = QtWidgets.QLineEdit(self)

        # 设置控件属性
        self.name_edit.setPlaceholderText("请输入摄像头名称")
        self.IP_edit.setPlaceholderText("请输入摄像头IP")
        self.zhanghao_edit.setPlaceholderText("请输入摄像头账号")
        self.mima_edit.setPlaceholderText("请输入摄像头密码")

        # 将控件添加到表单布局
        self.form_layout.addRow("名称:", self.name_edit)
        self.form_layout.addRow("IP:", self.IP_edit)
        self.form_layout.addRow("账号:", self.zhanghao_edit)
        self.form_layout.addRow("密码:", self.mima_edit)

        # 创建按钮布局
        self.button_layout = QtWidgets.QHBoxLayout()
        self.main_layout.addLayout(self.button_layout)

        self.btn_video_add = QtWidgets.QPushButton("添加视频", self)
        self.btn_delete_video = QtWidgets.QPushButton("删除视频", self)
        self.btn_back = QtWidgets.QPushButton("关闭", self)

        # 将按钮添加到布局
        self.button_layout.addWidget(self.btn_video_add)
        self.button_layout.addWidget(self.btn_delete_video)
        self.button_layout.addWidget(self.btn_back)

        # 连接信号与槽
        self.btn_video_add.clicked.connect(self.video_add_cap)
        self.btn_delete_video.clicked.connect(self.video_del_cap)
        self.btn_back.clicked.connect(lambda: self.change_video_show(self.mainwindow, self))

        # 设置样式
        self.setStyleSheet(widget_css)

    def video_add_cap(self): # 添加摄像头对象
        if self.name_edit.text()=='': # 判断名称是否为空
            print("error name is None")
            return

        if self.IP_edit.text()=='': # 判断IP是否为空
            print("error IP is None")
            return

        for key,value in self.video_cap_list.items():
            if self.name_edit.text()==key:
                print("name is exist")
                return
        self.video_cap_list[self.name_edit.text()]=[self.IP_edit.text(),self.zhanghao_edit.text(),self.mima_edit.text()]
        self.sql_class.cap_insert(self.name_edit.text(),self.IP_edit.text(),self.zhanghao_edit.text(),self.mima_edit.text())
        self.sql_class.read_cap_list()
        self.mainwindow.create_label()
        print("添加摄像头成功")
        print(self.video_cap_list)

    def video_del_cap(self): #删除摄像头对象
        if self.name_edit.text()=='':
            print("error name is None")
            return
        for key,value in self.video_cap_list.items():
            if self.name_edit.text()==key:
                del self.video_cap_list[key]
                self.sql_class.cap_delete(key)
                print("delete success")
                self.mainwindow.create_label()
                return

        print("delete false----- ",self.name_edit.text()," is not exist")

    def change_video_show(self, show, close):
        show.show()
        close.hide()