# Form implementation generated from reading ui file 'video_change.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_video_change(object):
    def setupUi(self, video_change):
        video_change.setObjectName("video_change")
        video_change.resize(401, 300)
        self.back = QtWidgets.QPushButton(parent=video_change)
        self.back.setGeometry(QtCore.QRect(240, 230, 75, 24))
        self.back.setObjectName("back")
        self.delete_video = QtWidgets.QPushButton(parent=video_change)
        self.delete_video.setGeometry(QtCore.QRect(159, 230, 75, 24))
        self.delete_video.setObjectName("delete_video")
        self.video_add = QtWidgets.QPushButton(parent=video_change)
        self.video_add.setGeometry(QtCore.QRect(78, 230, 75, 24))
        self.video_add.setObjectName("video_add")
        self.IP_edit = QtWidgets.QLineEdit(parent=video_change)
        self.IP_edit.setGeometry(QtCore.QRect(170, 70, 113, 20))
        self.IP_edit.setObjectName("IP_edit")
        self.zhanghao_edit = QtWidgets.QLineEdit(parent=video_change)
        self.zhanghao_edit.setGeometry(QtCore.QRect(170, 110, 113, 20))
        self.zhanghao_edit.setObjectName("zhanghao_edit")
        self.mima_edit = QtWidgets.QLineEdit(parent=video_change)
        self.mima_edit.setGeometry(QtCore.QRect(170, 150, 113, 20))
        self.mima_edit.setObjectName("mima_edit")
        self.IP = QtWidgets.QLabel(parent=video_change)
        self.IP.setGeometry(QtCore.QRect(100, 70, 54, 16))
        self.IP.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.IP.setObjectName("IP")
        self.zhanghao = QtWidgets.QLabel(parent=video_change)
        self.zhanghao.setGeometry(QtCore.QRect(100, 110, 54, 16))
        self.zhanghao.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.zhanghao.setObjectName("zhanghao")
        self.mima = QtWidgets.QLabel(parent=video_change)
        self.mima.setGeometry(QtCore.QRect(100, 150, 54, 16))
        self.mima.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mima.setObjectName("mima")

        self.retranslateUi(video_change)
        QtCore.QMetaObject.connectSlotsByName(video_change)

    def retranslateUi(self, video_change):
        _translate = QtCore.QCoreApplication.translate
        video_change.setWindowTitle(_translate("video_change", "Form"))
        self.back.setText(_translate("video_change", "close"))
        self.delete_video.setText(_translate("video_change", "delete"))
        self.video_add.setText(_translate("video_change", "add_video"))
        self.IP.setText(_translate("video_change", "IP"))
        self.zhanghao.setText(_translate("video_change", "账号"))
        self.mima.setText(_translate("video_change", "密码"))



class Ui_video_change_1(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setObjectName("video_change")
        self.resize(401, 300)
        self.back = QtWidgets.QPushButton(parent=self)
        self.back.setGeometry(QtCore.QRect(240, 230, 75, 24))
        self.back.setObjectName("back")
        self.delete_video = QtWidgets.QPushButton(parent=self)
        self.delete_video.setGeometry(QtCore.QRect(159, 230, 75, 24))
        self.delete_video.setObjectName("delete_video")
        self.video_add = QtWidgets.QPushButton(parent=self)
        self.video_add.setGeometry(QtCore.QRect(78, 230, 75, 24))
        self.video_add.setObjectName("video_add")
        self.IP_edit = QtWidgets.QLineEdit(parent=self)
        self.IP_edit.setGeometry(QtCore.QRect(170, 70, 113, 20))
        self.IP_edit.setObjectName("IP_edit")
        self.zhanghao_edit = QtWidgets.QLineEdit(parent=self)
        self.zhanghao_edit.setGeometry(QtCore.QRect(170, 110, 113, 20))
        self.zhanghao_edit.setObjectName("zhanghao_edit")
        self.mima_edit = QtWidgets.QLineEdit(parent=self)
        self.mima_edit.setGeometry(QtCore.QRect(170, 150, 113, 20))
        self.mima_edit.setObjectName("mima_edit")
        self.IP = QtWidgets.QLabel(parent=self)
        self.IP.setGeometry(QtCore.QRect(100, 70, 54, 16))
        self.IP.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.IP.setObjectName("IP")
        self.zhanghao = QtWidgets.QLabel(parent=self)
        self.zhanghao.setGeometry(QtCore.QRect(100, 110, 54, 16))
        self.zhanghao.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.zhanghao.setObjectName("zhanghao")
        self.mima = QtWidgets.QLabel(parent=self)
        self.mima.setGeometry(QtCore.QRect(100, 150, 54, 16))
        self.mima.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mima.setObjectName("mima")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("video_change", "Form"))
        self.back.setText(_translate("video_change", "close"))
        self.delete_video.setText(_translate("video_change", "delete"))
        self.video_add.setText(_translate("video_change", "add_video"))
        self.IP.setText(_translate("video_change", "IP"))
        self.zhanghao.setText(_translate("video_change", "账号"))
        self.mima.setText(_translate("video_change", "密码"))